spring:
  profiles:
    include:
      - comm
---
server:
  config:
    activate:
      on-profile: prod
  port: 8080
  error.include-message: always
  tomcat:
    max-swallow-size: -1
  reactive:
    session:
      cookie:
        domain: .profilehub.info
        secure: true
---
logging:
  level:
    root: DEBUG
---
server:
  config:
    activate:
      on-profile: local
  port: 7002

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/profile_box
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
