name: 'push-update'

on:
  push:
    branches: [ main ]

env:
  ORGANIZATION: k8s12-CacaoEnt
  ROOT: profilehub
  ADMIN: profile-box-api-admin
  COMM: profile-box-comm
  GITOPS_REPOSITORY: profile-box-gitops
  GITOPS_DIR: gitops/api-admin/prod
  GITOPS_YAML_FILE: deployment.yaml
  AWS_REGION: ap-northeast-2
  AWS_ECR_PATH: 204770130849.dkr.ecr.ap-northeast-2.amazonaws.com/rofile-box-admin

jobs:
  build-image-push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: checkout root
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ORGANIZATION }}/${{ env.ROOT }}
          ref: main

      - name: checkout comm
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ORGANIZATION }}/${{ env.COMM }}
          ref: main
          path: ${{ env.COMM }}

      - name: checkout admin
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ORGANIZATION }}/${{ env.ADMIN }}
          ref: main
          path: ${{ env.ADMIN }}

#      - name: checkout gitops
#        uses: actions/checkout@v3
#        with:
#          repository: ${{ env.ORGANIZATION_NAME }}/${{ env.GITOPS_REPOSITORY }}
#          ref: main
#          path: ${{ env.GITOPS_REPOSITORY }}
#          token: ${{secrets.GIT_TOKEN}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          cd ${{ env.USER_GIT }}
          pwd
          docker build --no-cache -t ${{ env.AWS_ECR_PATH }}:latest .}
          docker push ${{ env.AWS_ECR_PATH }}:latest

#      - name: Update GitOps YAML Version and Commit
#        run: |
#          cd ${{ env.GITOPS_REPOSITORY }}/${{ env.GITOPS_DIR }}
#          sed -i 's/${{ env.AWS_ECR_REPOSITORY }}:.*/${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMG_TAG }}/' ${{env.GITOPS_YAML_FILE}}
#          cd ../../../
#          git config user.name ${{ secrets.USER_NAME }}
#          git config user.email ${{ secrets.USER_EMAIL }}
#          git add ${{ env.GITOPS_DIR }}/${{ env.GITOPS_YAML_FILE }}
#          git commit -m "Update YAML Image Tag To ${{ env.IMG_TAG }}"
#          git push origin main